
Name: Faraz ali
Roll: PIAIC57145
Assignment 1 Batch 4 Quarter 2

In [2]:
# Importing numpy library as rusel
import numpy as np

In [3]:
#method 1
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#method 2
np.add(8,2)

10

In [5]:
#method 3
np.subtract(15,7)

8

In [6]:
#method 4
np.multiply(4,2)

8

In [7]:
#method 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
#method 6
np.ones(1)

array([1.])

In [9]:
#method 7
np.ones((5,4),dtype=float)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#method 8
np.full((5,4),7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
#method 9
np.arange(5,30,4)

array([ 5,  9, 13, 17, 21, 25, 29])

In [12]:
#method 10
np.linspace(0,5,5)


array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [13]:
#method 11
np.random.random((3,2))



array([[0.30037486, 0.93606687],
       [0.26290252, 0.89695343],
       [0.20008227, 0.63395864]])

In [14]:
#method 12
x=np.empty(7)
x


array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.78287341e-307])

In [15]:
#method 13
y=np.empty(2)
y


array([6.85216574e+256, 9.75001017e+020])

In [16]:
#method 14
rint=np.random.randint(0,20,(5,5))
rint


array([[13, 16,  9,  2, 16],
       [ 5, 11, 14, 16, 14],
       [ 2,  9, 11,  7, 13],
       [ 2,  4,  3,  8,  2],
       [17,  0,  7,  8, 11]])

In [17]:
#method 15
np.shape(x)


(7,)

In [18]:
#method 16
np.size(x)


7

In [19]:
#method 17
print(x.dtype)
print(y.dtype)
print(rint.dtype)



float64
float64
int32


In [20]:
#method 18
print(x.data)
print(y.data)
print(rint.data)


In [22]:
#method 19
print(x.itemsize)
print(y.itemsize)
print(rint.itemsize)


8
8
4


In [23]:
#method 20
print(x.ndim)
print(y.ndim)
print(rint.ndim)


1
1
2


In [24]:
#method 21
np.random.default_rng(1)


Generator(PCG64) at 0x1DC3339BA98

In [25]:
#method 22
new=np.random.randint(11,20,(5,5))


In [26]:
#method 23
new.min()


11

In [27]:
#method 24
new.max()


19

In [28]:
#method 25
new.mean()


15.36

In [29]:
#method 26
new.sum()


384

In [30]:
#method 27
np.exp(new)


array([[8.88611052e+06, 1.78482301e+08, 1.62754791e+05, 8.88611052e+06,
        1.62754791e+05],
       [1.20260428e+06, 5.98741417e+04, 6.56599691e+07, 6.56599691e+07,
        2.41549528e+07],
       [2.41549528e+07, 1.62754791e+05, 8.88611052e+06, 6.56599691e+07,
        1.62754791e+05],
       [2.41549528e+07, 1.20260428e+06, 5.98741417e+04, 1.62754791e+05,
        1.78482301e+08],
       [8.88611052e+06, 1.78482301e+08, 2.41549528e+07, 2.41549528e+07,
        1.20260428e+06]])

In [31]:
#method 28
np.random.seed(0)
np.random.random((2,5))


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]])

In [32]:
#method 29
new.ravel()


array([16, 19, 12, 16, 12, 14, 11, 18, 18, 17, 17, 12, 16, 18, 12, 17, 14,
       11, 12, 19, 16, 19, 17, 17, 14])

In [33]:
#method 30
np.abs(new)


array([[16, 19, 12, 16, 12],
       [14, 11, 18, 18, 17],
       [17, 12, 16, 18, 12],
       [17, 14, 11, 12, 19],
       [16, 19, 17, 17, 14]])

In [34]:
#method 31
np.pi


3.141592653589793

In [35]:
#method 32
np.sin(new)


array([[-0.28790332,  0.14987721, -0.53657292, -0.28790332, -0.53657292],
       [ 0.99060736, -0.99999021, -0.75098725, -0.75098725, -0.96139749],
       [-0.96139749, -0.53657292, -0.28790332, -0.75098725, -0.53657292],
       [-0.96139749,  0.99060736, -0.99999021, -0.53657292,  0.14987721],
       [-0.28790332,  0.14987721, -0.96139749, -0.96139749,  0.99060736]])

In [36]:
#method 33
np.cos(new)


array([[-0.95765948,  0.98870462,  0.84385396, -0.95765948,  0.84385396],
       [ 0.13673722,  0.0044257 ,  0.66031671,  0.66031671, -0.27516334],
       [-0.27516334,  0.84385396, -0.95765948,  0.66031671,  0.84385396],
       [-0.27516334,  0.13673722,  0.0044257 ,  0.84385396,  0.98870462],
       [-0.95765948,  0.98870462, -0.27516334, -0.27516334,  0.13673722]])

In [37]:
#method 34
np.tan(new)


array([[ 3.00632242e-01,  1.51589471e-01, -6.35859929e-01,
         3.00632242e-01, -6.35859929e-01],
       [ 7.24460662e+00, -2.25950846e+02, -1.13731371e+00,
        -1.13731371e+00,  3.49391565e+00],
       [ 3.49391565e+00, -6.35859929e-01,  3.00632242e-01,
        -1.13731371e+00, -6.35859929e-01],
       [ 3.49391565e+00,  7.24460662e+00, -2.25950846e+02,
        -6.35859929e-01,  1.51589471e-01],
       [ 3.00632242e-01,  1.51589471e-01,  3.49391565e+00,
         3.49391565e+00,  7.24460662e+00]])

In [38]:
#method 35
np.arcsin(0.8)


0.9272952180016123

In [39]:
#method 36
np.arccos(0.8)


0.6435011087932843

In [40]:
#method 37
np.arctan(0.8)


0.6747409422235527

In [41]:
#method 38
np.log(new)


array([[2.77258872, 2.94443898, 2.48490665, 2.77258872, 2.48490665],
       [2.63905733, 2.39789527, 2.89037176, 2.89037176, 2.83321334],
       [2.83321334, 2.48490665, 2.77258872, 2.89037176, 2.48490665],
       [2.83321334, 2.63905733, 2.39789527, 2.48490665, 2.94443898],
       [2.77258872, 2.94443898, 2.83321334, 2.83321334, 2.63905733]])

In [42]:
#method 39
np.log2(new)


array([[4.        , 4.24792751, 3.5849625 , 4.        , 3.5849625 ],
       [3.80735492, 3.45943162, 4.169925  , 4.169925  , 4.08746284],
       [4.08746284, 3.5849625 , 4.        , 4.169925  , 3.5849625 ],
       [4.08746284, 3.80735492, 3.45943162, 3.5849625 , 4.24792751],
       [4.        , 4.24792751, 4.08746284, 4.08746284, 3.80735492]])

In [43]:
#method 40
np.log10(new)


array([[1.20411998, 1.2787536 , 1.07918125, 1.20411998, 1.07918125],
       [1.14612804, 1.04139269, 1.25527251, 1.25527251, 1.23044892],
       [1.23044892, 1.07918125, 1.20411998, 1.25527251, 1.07918125],
       [1.23044892, 1.14612804, 1.04139269, 1.07918125, 1.2787536 ],
       [1.20411998, 1.2787536 , 1.23044892, 1.23044892, 1.14612804]])

In [44]:
#method 41
np.add.reduce(new)


array([80, 75, 74, 81, 74])

In [45]:
#method 42
np.multiply.reduce(new)


array([1035776,  667128,  646272, 1057536,  651168])

In [46]:
#method 43
np.add.accumulate(new)


array([[16, 19, 12, 16, 12],
       [30, 30, 30, 34, 29],
       [47, 42, 46, 52, 41],
       [64, 56, 57, 64, 60],
       [80, 75, 74, 81, 74]], dtype=int32)

In [47]:
#method 44
np.multiply.accumulate(new)


array([[     16,      19,      12,      16,      12],
       [    224,     209,     216,     288,     204],
       [   3808,    2508,    3456,    5184,    2448],
       [  64736,   35112,   38016,   62208,   46512],
       [1035776,  667128,  646272, 1057536,  651168]], dtype=int32)

In [48]:
#method 45
np.power(2,3)


8

In [49]:
#method 46
np.hsplit(new,5)


[array([[16],
        [14],
        [17],
        [17],
        [16]]),
 array([[19],
        [11],
        [12],
        [14],
        [19]]),
 array([[12],
        [18],
        [16],
        [11],
        [17]]),
 array([[16],
        [18],
        [18],
        [12],
        [17]]),
 array([[12],
        [17],
        [12],
        [19],
        [14]])]

In [50]:
#method 47
np.vsplit(new,5)


[array([[16, 19, 12, 16, 12]]),
 array([[14, 11, 18, 18, 17]]),
 array([[17, 12, 16, 18, 12]]),
 array([[17, 14, 11, 12, 19]]),
 array([[16, 19, 17, 17, 14]])]

In [51]:
#method 48
np.absolute(new)


array([[16, 19, 12, 16, 12],
       [14, 11, 18, 18, 17],
       [17, 12, 16, 18, 12],
       [17, 14, 11, 12, 19],
       [16, 19, 17, 17, 14]])

In [52]:
#method 49
np.prod(new)


0

In [53]:
#method 50
np.std(new)


2.651490147068248